module.exports = {
    REPLACE_TAG_WAIT_TIME: 4000, //TODO
    SPACE_TRIM_MAX_ITERATIONS: 10,
    // 666 Must be greater than SPACE_TRIM_INCREMENT_DOWN_FROM_THIS_FIRST
    SPACE_TRIM_INCREMENT_DOWN_FROM_THIS_FIRST: 3
}